apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfextract
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdfextract
  template:
    metadata:
      labels:
        app: pdfextract
    spec:
      containers:
      - name: pdfextract
        image: pdfextract
        imagePullPolicy: Never
        resources:
          limits:
            memory: 1000Mi
            cpu: 1000m
          requests:
            memory: 256Mi
            cpu: 125m
        ports:
        - containerPort: 3003


